"use client";
import { ArrowLeft, Shield, Trash2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Brand } from "./brand";
type Player={id:string;name:string;active:boolean;archived_at:string|null};
export function AdminView(){const[authenticated,setAuthenticated]=useState(false);const[pin,setPin]=useState("");const[players,setPlayers]=useState<Player[]>([]);const[timer,setTimer]=useState(15);const[error,setError]=useState("");const[newName,setNewName]=useState("");const[newPin,setNewPin]=useState("");
  const load=useCallback(async()=>{const[p,s]=await Promise.all([fetch("/api/admin/players"),fetch("/api/admin/settings")]);if(p.ok&&s.ok){setPlayers((await p.json()).players);const settings=await s.json();setTimer(settings.bidding_timer_seconds);setAuthenticated(true);}},[]);useEffect(()=>{void load();},[load]);
  async function login(e:React.FormEvent){e.preventDefault();const response=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({pin})});const body=await response.json();if(!response.ok)return setError(body.error);setPin("");void load();}
  async function patchPlayer(id:string,update:Record<string,unknown>){const response=await fetch("/api/admin/players",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...update})});const body=await response.json();if(!response.ok)return setError(body.error);void load();}
  async function addPlayer(e:React.FormEvent){e.preventDefault();const response=await fetch("/api/admin/players",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:newName,pin:newPin})});const body=await response.json();if(!response.ok)return setError(body.error);setNewName("");setNewPin("");void load();}
  async function removePlayer(id:string){if(!confirm("Delete this player? Players with results can only be archived."))return;const response=await fetch("/api/admin/players",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});const body=await response.json();if(!response.ok)return setError(body.error);void load();}
  async function saveTimer(value:number){setTimer(value);await fetch("/api/admin/settings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({biddingTimerSeconds:value})});}
  async function abandon(){if(confirm("Abandon the active game? It will not count toward stats."))await fetch("/api/admin/abandon",{method:"POST"});}
  if(!authenticated)return <main className="ambient login-wrap"><section className="panel login-card"><a className="back-link" href="/"><ArrowLeft size={16}/>Home</a><Shield color="var(--gold)"/><div className="eyebrow">Separate access</div><h2>Administrator</h2><form className="form-stack" onSubmit={login}><div className="field"><label>Admin PIN</label><input inputMode="numeric" type="password" maxLength={4} value={pin} onChange={(e)=>setPin(e.target.value.replace(/\D/g,""))}/></div><div className="error">{error}</div><button className="button" disabled={pin.length!==4}>Unlock</button></form></section></main>;
  return <main className="ambient"><div className="shell"><header className="topbar"><Brand/><a className="button ghost" href="/"><ArrowLeft size={16}/>Home</a></header><section className="page-section admin-page"><div className="eyebrow">Administration</div><h1>Table settings</h1><section className="panel admin-section"><h3>Bidding timer</h3><select value={timer} onChange={(e)=>saveTimer(Number(e.target.value))}>{[0,5,10,15,20,30,45,60].map(value=><option value={value} key={value}>{value===0?"Off":`${value} seconds`}</option>)}</select></section><section className="panel admin-section"><h3>Players</h3>{players.map(player=><div className="admin-player" key={player.id}><div><strong>{player.name}</strong><small>{player.archived_at?"Archived":player.active?"Active":"Inactive"}</small></div><button onClick={()=>{const next=prompt(`New 4-digit PIN for ${player.name}`);if(next)void patchPlayer(player.id,{pin:next});}}>PIN</button><button onClick={()=>patchPlayer(player.id,{active:!player.active})}>{player.active?"Disable":"Enable"}</button><button onClick={()=>patchPlayer(player.id,{archived:!player.archived_at})}>{player.archived_at?"Restore":"Archive"}</button><button className="danger-text" onClick={()=>removePlayer(player.id)}><Trash2 size={16}/></button></div>)}<form className="add-player" onSubmit={addPlayer}><input placeholder="New player name" value={newName} onChange={(e)=>setNewName(e.target.value)}/><input placeholder="4-digit PIN" inputMode="numeric" maxLength={4} value={newPin} onChange={(e)=>setNewPin(e.target.value.replace(/\D/g,""))}/><button className="button" disabled={!newName||newPin.length!==4}>Add player</button></form></section><button className="button danger ready-button" onClick={abandon}>Abandon active game</button><p className="error">{error}</p></section></div></main>;}
