"use client";
import { House, Minus, Plus, RotateCcw, Shield, UserPlus } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
type Player={id:string;name:string;active:boolean;archived_at:string|null;has_history:boolean};
type FormMode="none"|"pin"|"add";

export function AdminView(){
  const router=useRouter(); const[authenticated,setAuthenticated]=useState(false);const[pin,setPin]=useState("");const[players,setPlayers]=useState<Player[]>([]);const[timer,setTimer]=useState(20);const[scoreboardTimer,setScoreboardTimer]=useState(30);const[error,setError]=useState("");const[selectedId,setSelectedId]=useState("");const[mode,setMode]=useState<FormMode>("none");const[firstPin,setFirstPin]=useState("");const[confirmPin,setConfirmPin]=useState("");const[newName,setNewName]=useState("");const[hasActiveGame,setHasActiveGame]=useState(false);const[resetTarget,setResetTarget]=useState<Player|null>(null);const[resetting,setResetting]=useState(false);
  const selected=useMemo(()=>players.find(player=>player.id===selectedId),[players,selectedId]);
  const load=useCallback(async()=>{const[p,s,g]=await Promise.all([fetch("/api/admin/players"),fetch("/api/admin/settings"),fetch("/api/games/current")]);if(p.ok&&s.ok){const playerBody=await p.json();const settings=await s.json();setPlayers(playerBody.players);setTimer(settings.bidding_timer_seconds);setScoreboardTimer(settings.scoreboard_timer_seconds??30);setAuthenticated(true);setHasActiveGame(Boolean((await g.json()).game));}},[]);useEffect(()=>{void load();},[load]);
  async function login(e:React.FormEvent){e.preventDefault();setError("");const response=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({pin})});const body=await response.json();if(!response.ok)return setError(body.error);setPin("");void load();}
  async function saveTimer(next:number){next=Math.max(5,Math.min(60,next));setTimer(next);const response=await fetch("/api/admin/settings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({biddingTimerSeconds:next})});if(!response.ok)setError((await response.json()).error);}
  async function saveScoreboardTimer(next:number){next=Math.max(5,Math.min(60,next));setScoreboardTimer(next);const response=await fetch("/api/admin/settings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({scoreboardTimerSeconds:next})});if(!response.ok)setError((await response.json()).error);}
  async function patchPlayer(update:Record<string,unknown>){if(!selected)return;const response=await fetch("/api/admin/players",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:selected.id,...update})});const body=await response.json();if(!response.ok)return setError(body.error);setMode("none");setFirstPin("");setConfirmPin("");void load();}
  async function updatePin(e:React.FormEvent){e.preventDefault();setError("");if(firstPin!==confirmPin)return setError("PINs do not match");await patchPlayer({pin:firstPin});}
  async function archiveOrDelete(){if(!selected)return;const archive=selected.has_history;const message=archive?`Archive ${selected.name}? Their statistics will be retained.`:`Delete ${selected.name}? This cannot be undone.`;if(!confirm(message))return;const response=await fetch("/api/admin/players",{method:archive?"PATCH":"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify(archive?{id:selected.id,archived:true}:{id:selected.id})});const body=await response.json();if(!response.ok)return setError(body.error);setSelectedId("");setMode("none");void load();}
  async function addPlayer(e:React.FormEvent){e.preventDefault();setError("");if(firstPin!==confirmPin)return setError("PINs do not match");const response=await fetch("/api/admin/players",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:newName,pin:firstPin})});const body=await response.json();if(!response.ok)return setError(body.error);setNewName("");setFirstPin("");setConfirmPin("");setMode("none");void load();}
  async function abandon(){if(!confirm("Abandon this game? The game will end immediately and no statistics will be recorded."))return;const response=await fetch("/api/admin/abandon",{method:"POST"});if(!response.ok)return setError((await response.json()).error);router.replace("/");router.refresh();}
  async function resetStats(){if(!resetTarget)return;setResetting(true);setError("");const response=await fetch(`/api/admin/players/${resetTarget.id}/reset-stats`,{method:"POST"});const body=await response.json();setResetting(false);if(!response.ok)return setError(body.error);setResetTarget(null);void load();router.refresh();}
  if(!authenticated)return <main className="landscape-page centered-page"><a className="icon-link corner-home" href="/" aria-label="Home"><House/></a><form className="minimal-form clean-form" onSubmit={login}><Shield className="admin-shield"/><label>Admin PIN<input inputMode="numeric" type="password" maxLength={4} value={pin} onChange={(e)=>setPin(e.target.value.replace(/\D/g,""))}/></label><button className="primary-button" disabled={pin.length!==4}>Continue</button><p className="form-error">{error}</p></form></main>;
  return <main className="landscape-page admin-page"><a className="icon-link corner-home" href="/" aria-label="Home"><House/></a><section className="admin-layout"><div className="admin-timers"><TimerControl label="Bidding Timer" value={timer} onChange={saveTimer}/><TimerControl label="Scoreboard Timer" value={scoreboardTimer} onChange={saveScoreboardTimer}/>{hasActiveGame&&<button className="danger-button" onClick={abandon}>Abandon Game</button>}</div><div className="player-manager"><h2>Players</h2><select value={selectedId} onChange={e=>{setSelectedId(e.target.value);setMode("none");}}><option value="">Select player</option>{players.filter(p=>!p.archived_at).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select>{selected&&mode==="none"&&<div className="manager-actions"><button className="secondary-button" onClick={()=>setMode("pin")}>Change PIN</button><button className="secondary-button" onClick={()=>setResetTarget(selected)}><RotateCcw/>Reset Stats</button><button className="danger-button manager-wide" onClick={archiveOrDelete}>{selected.has_history?"Archive Player":"Delete Player"}</button></div>}{mode==="pin"&&<PinFields first={firstPin} confirmValue={confirmPin} setFirst={setFirstPin} setConfirm={setConfirmPin} submit="Update" onSubmit={updatePin}/>}<button className="text-button add-trigger" onClick={()=>{setMode("add");setSelectedId("");setFirstPin("");setConfirmPin("");}}><UserPlus/>Add Player</button>{mode==="add"&&<form className="inline-pin-form" onSubmit={addPlayer}><label>Player Name<input value={newName} onChange={e=>setNewName(e.target.value)} maxLength={40}/></label><PinInputs first={firstPin} confirmValue={confirmPin} setFirst={setFirstPin} setConfirm={setConfirmPin}/><button className="primary-button" disabled={!newName.trim()||firstPin.length!==4||confirmPin.length!==4}>Add</button></form>}<p className="form-error">{error}</p></div></section>{resetTarget&&<div className="modal-backdrop"><section className="brand-modal reset-stats-modal"><h2>Reset all statistics for {resetTarget.name}?</h2><p>This keeps the player and PIN, but removes all completed results from their Stats totals.</p><div className="confirm-actions"><button className="secondary-button" disabled={resetting} onClick={()=>setResetTarget(null)}>Cancel</button><button className="danger-button" disabled={resetting} onClick={()=>void resetStats()}>{resetting?"Resetting…":"Reset Stats"}</button></div></section></div>}</main>;
}
function TimerControl({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>Promise<void>}){return <div className="admin-timer"><h1>{label}</h1><div className="stepper timer-stepper"><button onClick={()=>void onChange(value-5)} disabled={value<=5}><Minus/></button><strong>{value} seconds</strong><button onClick={()=>void onChange(value+5)} disabled={value>=60}><Plus/></button></div></div>}
function PinInputs({first,confirmValue,setFirst,setConfirm}:{first:string;confirmValue:string;setFirst:(v:string)=>void;setConfirm:(v:string)=>void}){return <><label>New 4-digit PIN<input inputMode="numeric" type="password" maxLength={4} value={first} onChange={e=>setFirst(e.target.value.replace(/\D/g,""))}/></label><label>Confirm 4-digit PIN<input inputMode="numeric" type="password" maxLength={4} value={confirmValue} onChange={e=>setConfirm(e.target.value.replace(/\D/g,""))}/></label></>}
function PinFields(props:{first:string;confirmValue:string;setFirst:(v:string)=>void;setConfirm:(v:string)=>void;submit:string;onSubmit:(e:React.FormEvent)=>void}){return <form className="inline-pin-form" onSubmit={props.onSubmit}><PinInputs {...props}/><button className="primary-button" disabled={props.first.length!==4||props.confirmValue.length!==4}>{props.submit}</button></form>}
