"use client";
import { BarChart3, LogOut, Plus, Shield, Users, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Brand } from "./brand";

export function Dashboard({playerName}:{playerName:string|null}){
  const router=useRouter();const[creating,setCreating]=useState(false);const[mode,setMode]=useState<"custom"|"half"|"full">("custom");const[customRounds,setCustomRounds]=useState(10);const[error,setError]=useState("");const[existing,setExisting]=useState(false);const[busy,setBusy]=useState(false);
  async function create(forceNew=false){if(!playerName)return router.push("/login");setBusy(true);setError("");const response=await fetch("/api/games/current/create",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode,customRounds,forceNew})});const body=await response.json();setBusy(false);if(response.status===409){setExisting(true);return;}if(!response.ok)return setError(body.error);router.push("/lobby");}
  async function resume(){const response=await fetch("/api/games/current/join",{method:"POST",headers:{"content-type":"application/json"},body:"{}"});const body=await response.json();if(!response.ok)return setError(body.error);router.push("/lobby");}
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.refresh();}
  return <main className="ambient mobile-home"><div className="shell"><header className="topbar"><Brand/>{playerName?<button className="button ghost icon-button" onClick={logout} aria-label="Switch player"><LogOut size={18}/></button>:<a className="small-login" href="/login">Sign in</a>}</header><section className="mobile-hero"><div className="eyebrow">{playerName?`Ready, ${playerName}?`:"Private game · 3–4 players"}</div><h1>Call it<br/>exactly.</h1><p className="subtle">Your table, your judgement, your bragging rights.</p></section><section className="mobile-actions"><button onClick={()=>setCreating(true)}><Plus/><span>Create</span></button><button onClick={()=>router.push("/join")}><Users/><span>Join</span></button><button onClick={()=>router.push("/stats")}><BarChart3/><span>Stats</span></button></section><a className="admin-link" href="/admin"><Shield size={14}/> Admin</a></div>
  {creating&&<div className="modal-backdrop"><section className="panel modal create-modal"><button className="button ghost modal-close" onClick={()=>setCreating(false)}><X/></button><div className="eyebrow">New game</div><h2>Choose the rounds</h2><div className="mode-picker">{(["custom","half","full"] as const).map(value=><button className={mode===value?"active":""} onClick={()=>setMode(value)} key={value}>{value}</button>)}</div>{mode==="custom"&&<div className="round-stepper"><button onClick={()=>setCustomRounds(Math.max(1,customRounds-1))}>−</button><div><strong>{customRounds}</strong><span>rounds</span></div><button onClick={()=>setCustomRounds(Math.min(17,customRounds+1))}>+</button></div>}<p className="subtle mode-note">{mode==="half"?"1 up to the maximum hand":mode==="full"?"Maximum down to 1, then back up":"1 card up to your chosen number"}</p>{existing?<div className="existing-actions"><p>An unfinished game already exists.</p><button className="button secondary" onClick={resume}>Resume existing</button><button className="button danger" onClick={()=>create(true)}>Abandon it & start new</button></div>:<button className="button ready-button" onClick={()=>create()} disabled={busy}>{busy?"Creating…":"Create lobby"}</button>}<div className="error">{error}</div></section></div>}
  </main>;
}
