"use client";
import { Check, LoaderCircle, Minus, Plus, Wifi, WifiOff, X } from "lucide-react";
import { AnimatePresence, motion } from "framer-motion";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createClient } from "@supabase/supabase-js";
import type { Card, ClientGameState, RoundScoreSnapshot } from "@/lib/game/types";
import { PlayingCard } from "./playing-card";

type ActionInput = { type: "place_bid"; bid: number } | { type: "play_card"; card: Card } | { type: "scorecard_ready" } | { type: "end_game" };
const cid = (card: Card) => `${card.rank}-${card.suit}`;
const suitLabel = { clubs: "♣ CLUBS", diamonds: "♦ DIAMONDS", hearts: "♥ HEARTS", spades: "♠ SPADES" } as const;
const vibrate = (pattern:number|number[]) => { if (typeof navigator!=="undefined" && "vibrate" in navigator) navigator.vibrate(pattern); };

export function GameTable({ gameId }: { gameId: string }) {
  const [state,setState]=useState<ClientGameState|null>(null);const[participantId,setParticipantId]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[now,setNow]=useState(Date.now());const[bidValue,setBidValue]=useState(0);const[showEnd,setShowEnd]=useState(false);const[autoBidNotice,setAutoBidNotice]=useState(false);const lastUrgent=useRef<number|null>(null);
  const load=useCallback(async()=>{const response=await fetch(`/api/games/${gameId}/state`,{cache:"no-store"});const body=await response.json();if(response.ok){setState(body.state);setParticipantId(body.participantId);setError("");}else setError(body.error);},[gameId]);
  useEffect(()=>{void load();const poll=setInterval(load,2500);const clock=setInterval(()=>setNow(Date.now()),200);const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;const client=url&&key?createClient(url,key):null;const channel=client?.channel(`game-${gameId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"game_updates",filter:`game_id=eq.${gameId}`},()=>void load()).subscribe();const resume=()=>{if(document.visibilityState==="visible")void load();};document.addEventListener("visibilitychange",resume);window.addEventListener("pageshow",resume);window.addEventListener("online",resume);return()=>{clearInterval(poll);clearInterval(clock);document.removeEventListener("visibilitychange",resume);window.removeEventListener("pageshow",resume);window.removeEventListener("online",resume);if(client&&channel)void client.removeChannel(channel);};},[gameId,load]);
  useEffect(()=>{setBidValue(0);},[state?.roundNumber]);
  useEffect(()=>{const seconds=state?.biddingEndsAt?Math.max(0,Math.ceil((new Date(state.biddingEndsAt).getTime()-now)/1000)):null;if(seconds!==null&&seconds<=5&&seconds>0&&lastUrgent.current!==seconds){lastUrgent.current=seconds;vibrate(10);}},[state?.biddingEndsAt,now]);
  useEffect(()=>{if(state?.phase==="trick_complete"&&state.trickWinnerId===participantId)vibrate([18,28,18]);if(state?.phase==="game_complete")vibrate([25,35,25]);},[state?.phase,state?.trickWinnerId,participantId]);
  useEffect(()=>{if(!state?.trickEndsAt)return;const delay=Math.max(0,new Date(state.trickEndsAt).getTime()-Date.now()+60);const timer=setTimeout(()=>void load(),delay);return()=>clearTimeout(timer);},[state?.trickEndsAt,load]);
  useEffect(()=>{if(state?.phase!=="playing"||!state.autoBidPlayerIds.includes(participantId))return;setAutoBidNotice(true);const timer=setTimeout(()=>setAutoBidNotice(false),3000);return()=>clearTimeout(timer);},[state?.phase,state?.roundNumber,state?.autoBidPlayerIds.join(","),participantId]);
  async function act(action:ActionInput){if(busy)return;setBusy(true);setError("");const response=await fetch(`/api/games/${gameId}/action`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...action,actionId:crypto.randomUUID()})});const body=await response.json();setBusy(false);if(response.ok){setState(body.state);if(action.type==="play_card")vibrate(18);if(action.type==="place_bid")vibrate(12);if(action.type==="end_game")vibrate([30,40,30]);}else{setError(body.error);void load();}}
  const meIndex=state?.players.findIndex(p=>p.id===participantId)??0;const seats=useMemo(()=>state?.players.map((_,relative)=>state.players[(meIndex+relative)%state.players.length])??[],[state,meIndex]);
  if(!state)return <main className="game-page"><div className="center-message"><LoaderCircle className="spin"/><span>{error||"Reconnecting…"}</span></div></main>;
  const locations=state.players.length===3?["bottom","upper-left","upper-right"]:["bottom","left","top","right"];const me=state.players[meIndex];const active=state.players[state.activePlayerIndex];const myTurn=state.phase==="playing"&&active.id===participantId;const bidSeconds=state.biddingEndsAt?Math.max(0,Math.ceil((new Date(state.biddingEndsAt).getTime()-now)/1000)):null;const scoreSeconds=state.scorecardEndsAt?Math.max(0,Math.ceil((new Date(state.scorecardEndsAt).getTime()-now)/1000)):0;const connected=(id:string)=>now-new Date(state.presence[id]??0).getTime()<20_000;const winners=state.phase==="game_complete"?state.players.filter(p=>p.totalScore===Math.max(...state.players.map(q=>q.totalScore))):[];
  const playCard=(card:Card)=>{if(!state.legalCardIds.includes(cid(card))||busy)return;void act({type:"play_card",card});};
  return <main className="game-page"><header className="game-hud"><div className="hud-badges"><span>R {state.roundNumber}/{state.roundSizes.length}</span><strong className={state.trump==="hearts"||state.trump==="diamonds"?"red-suit":""}>{suitLabel[state.trump]}</strong><span>{state.direction==="clockwise"?"↻ CLOCKWISE":"↺ COUNTER-CLOCKWISE"}</span></div><button className="end-game-link" onClick={()=>setShowEnd(true)}>End Game</button></header><section className="table-stage">
    {seats.map((player,relative)=><div className={`player-seat ${locations[relative]}`} key={player.id}><div className={`player-info ${active.id===player.id&&state.phase==="playing"?"active":""} ${state.trickWinnerId===player.id?"trick-winner":""}`}><span className={`connection ${connected(player.id)?"online":""}`}>{connected(player.id)?<Wifi/>:<WifiOff/>}</span><strong>{player.name}{player.id===participantId?" · You":""}</strong><small>{state.phase==="bidding"?(player.id===participantId&&player.bid!==null?"Bid submitted":player.id!==participantId&&player.bid!==null?"Ready":"Bidding"):`Bid ${player.bid??"–"} · Won ${player.tricksWon}`}</small>{state.dealerIndex===state.players.findIndex(p=>p.id===player.id)&&<b className="dealer-dot">D</b>}</div>{relative!==0&&<div className="card-backs">{Array.from({length:Math.min(state.opponentCardCounts[player.id]??0,5)},(_,i)=><i className="mini-back" key={i}/>)}</div>}{relative===0&&<div className={`hand ${state.hand.length>12?"two-row":""}`}>{state.hand.map((card,index)=>{const legal=state.legalCardIds.includes(cid(card));return <motion.button layout className={`hand-card ${legal?"legal":"illegal"}`} disabled={!legal||busy} onClick={()=>playCard(card)} key={cid(card)} style={{zIndex:index}} whileTap={legal?{y:-10}:undefined}><PlayingCard card={card}/></motion.button>;})}</div>}</div>)}
    <div className="trick-area"><AnimatePresence>{state.currentTrick.map(play=>{const relative=(state.players.findIndex(p=>p.id===play.playerId)-meIndex+state.players.length)%state.players.length;const position=state.players.length===3&&relative===2?3:relative;return <motion.div className={`played-card p${position} ${state.trickWinnerId===play.playerId?"winner":""}`} initial={{opacity:0,scale:.55,x:position===1?-70:position===3?70:0,y:position===0?70:position===2?-70:0}} animate={{opacity:1,scale:1,x:0,y:0}} exit={{opacity:0,scale:.5}} transition={{duration:.28}} key={`${play.playerId}-${cid(play.card)}`}><PlayingCard card={play.card}/></motion.div>;})}</AnimatePresence></div>
    {(state.phase==="playing"||state.phase==="trick_complete")&&<div className="turn-chip">{state.phase==="trick_complete"?`${state.players.find(p=>p.id===state.trickWinnerId)?.name} wins the trick`:myTurn?"Your turn":`${active.name}'s turn`}</div>}
    {state.phase==="bidding"&&<div className="bid-dock"><div className={`bid-timer ${bidSeconds!==null&&bidSeconds<=5?"urgent":""}`}>{bidSeconds??"–"}</div>{me.bid===null?<><div className="bid-stepper"><button onClick={()=>setBidValue(Math.max(0,bidValue-1))} disabled={bidValue===0}><Minus/></button><strong>{bidValue}</strong><button onClick={()=>setBidValue(Math.min(state.cardsDealt,bidValue+1))} disabled={bidValue===state.cardsDealt}><Plus/></button></div><button className="primary-button bid-submit" disabled={busy} onClick={()=>void act({type:"place_bid",bid:bidValue})}>Submit</button></>:<div className="bid-wait"><Check/>Bid submitted</div>}</div>}
    {autoBidNotice&&<div className="auto-bid-note">Time expired. Bid 0 submitted.</div>}
  </section>
  {state.phase==="round_complete"&&<Scoreboard state={state} history={state.scoreHistory??[]} countdown={scoreSeconds} ready={state.readyPlayerIds.includes(participantId)} onReady={()=>void act({type:"scorecard_ready"})}/>} {state.phase==="game_complete"&&<Scoreboard state={state} history={state.scoreHistory??[]} final winners={winners.map(p=>p.id)} onReady={()=>location.assign("/")}/>} {showEnd&&<EndGameConfirm state={state} onCancel={()=>setShowEnd(false)} onConfirm={()=>{setShowEnd(false);void act({type:"end_game"});}}/>}{error&&<div className="toast-error">{error}</div>}</main>;
}

function Scoreboard({state,history,countdown,ready,final,winners=[],onReady}:{state:ClientGameState;history:RoundScoreSnapshot[];countdown?:number;ready?:boolean;final?:boolean;winners?:string[];onReady:()=>void}){return <div className="scoreboard-backdrop"><section className="scoreboard"><div className="scoreboard-title">{final?"Final Score Board":"Score Board"}{countdown!==undefined&&<span>{countdown}</span>}</div><div className="score-scroll"><table><thead><tr><th>Trump</th><th>Round</th>{state.players.map(p=><th className={winners.includes(p.id)?"winner-column":""} key={p.id}>{p.name}</th>)}</tr></thead><tbody>{history.map(round=><tr key={round.roundNumber}><td className={round.trump==="hearts"||round.trump==="diamonds"?"red-suit":""}>{suitLabel[round.trump]}</td><td>{round.roundNumber}</td>{state.players.map(p=><td className={winners.includes(p.id)?"winner-column":""} key={p.id}>{round.results.find(r=>r.playerId===p.id)?.roundScore??""}</td>)}</tr>)}</tbody><tfoot><tr><td></td><td>Total</td>{state.players.map(p=><td className={winners.includes(p.id)?"winner-column":""} key={p.id}>{p.totalScore}</td>)}</tr></tfoot></table></div><button className="primary-button scoreboard-ok" disabled={ready} onClick={onReady}>{ready?"Ready ✓":"OK"}</button></section></div>}
function EndGameConfirm({state,onCancel,onConfirm}:{state:ClientGameState;onCancel:()=>void;onConfirm:()=>void}){return <div className="modal-backdrop"><section className="brand-modal end-confirm"><button className="icon-link modal-close" onClick={onCancel}><X/></button><h2>End this game?</h2><div className="standings">{[...state.players].sort((a,b)=>b.totalScore-a.totalScore).map(p=><div key={p.id}><span>{p.name}</span><strong>{p.totalScore}</strong></div>)}</div><p>Current scores become final and statistics will be recorded.</p><div className="confirm-actions"><button className="secondary-button" onClick={onCancel}>Cancel</button><button className="danger-button" onClick={onConfirm}>End Game</button></div></section></div>}
